### PR TITLE
V10 compat

### PR DESCRIPTION
**Pull request by wickermoon**
A lot of fixes, so Token Action HUD won't throw errors left and right. :)

### CODE REVIEW

**Comment by Drental** [comment]
there are a lot of conflicts here, can you sort out if you did the same work that I merged earlier this evening? 😅 

Thank you anyway, I appreciate your time! :bow:

**Comment by wickermoon** [comment]
I based my branch off of master. I just checked master out again, to make sure I didn't miss any commits, but git tells me that I'm okay. I have no idea why there are conflicts :(

**Comment by wickermoon** [comment]
Okay, it was MOSTLY the same work, but I did catch some other places as well. ^^' The only thing I'm not too sure about is, that I removed the special treatment of spell items. calling "item.use({event});" seems to work just as fine as simply calling item.use() and means it's a boolean check less.

**Comment by Drental** [comment]
looks good now :bow: thank you again.

**Pull request merged**
