### PR TITLE
Swn

### PR DESCRIPTION
**Pull request by thebwt**
I've done an initial implementation of the SWNR system. 

It works for PCs and NPCs as per the system standard, then for ships/vehicles per the more updated version at https://github.com/wintersleepAI/foundry-swnr

### CODE REVIEW

**Review by Larkinabout — APPROVED** [review]
Looks good.

**Comment by Larkinabout** [comment]
Hi @thebwt, would you be interested in developing a Token Action HUD SWN module to work with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core)?

It should just be a case of shifting the SWN-specific code over and updating to some new core functions. You can use [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) as a starting point. The only real requirement is the module id as the core module looks for the system module in the format: token-action-hud-system where system is the system id, e.g., token-action-hud-swn.

If you're interested, let me know and I can help with getting started. I won't have the time to get to it myself anytime soon, so best for someone that supports the system.

**Comment by thebwt** [comment]
Sure! I really didn't know if what I did should have been a module or directly in the main project.

Did I cause some issues or is there just a larger project to get things out of core.

**Comment by Larkinabout** [comment]
I've started to split the core functions from the system functions, so the new method will be to install Token Action HUD Core and then only install the Token Action HUD system module for the system you're using, rather than installing all of them. It also means other people can develop and maintain their system module without having to wait for fixes to other systems.

No issues caused, I just wanted to ask you while it's still fresh your mind and I've also just released an update to Token Action HUD Core, so now is a good time to start development.

**Comment by thebwt** [comment]
Oh heck yea, I'll fire that up over the next week.

**Pull request merged**
