### PR TITLE
Add support for 'cyphersystem'

### PR DESCRIPTION
**Pull request by farling42**
This pull request adds support for the cyphersystem game system, version 2.1.0 and later

### CODE REVIEW

**Comment by Larkinabout** [comment]
Hi @farling42, would you be interested in developing a Token Action HUD Cypher System module to work with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core)?

It should just be a case of shifting the Cypher System-specific code over and updating to some new core functions. You can use [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) as a starting point. The only real requirement is the module id as the core module looks for the system module in the format: token-action-hud-system where system is the system id, e.g., token-action-hud-cyphersystem.

If you're interested, let me know and I can help with getting started. I won't have the time to get to it myself anytime soon, so best for someone that supports the system.

**Comment by farling42** [comment]
> Hi @farling42, would you be interested in developing a Token Action HUD Cypher System module to work with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core)?
> 
> It should just be a case of shifting the Cypher System-specific code over and updating to some new core functions. You can use [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) as a starting point. The only real requirement is the module id as the core module looks for the system module in the format: token-action-hud-system where system is the system id, e.g., token-action-hud-cyphersystem.
> 
> If you're interested, let me know and I can help with getting started. I won't have the time to get to it myself anytime soon, so best for someone that supports the system.

Hi, I've had a brief look at the token-action-hud-core module, and it seems to make too many assumptions about the files present in the dependent modules. i.e. a 'scripts/constants.js' file as well as a 'scripts.${systemModuleId}.min.js' script.

I don't use any form of rollup mechanism to generated min.js files. It is just extra overhead that I don't think is required for my modules.

Is there a reason that you don't create a new Hook for a dependent module to hook onto, and then the hook function can call your register function and pass you the relevant SystemManager class? This would avoid you having to specify the specific module naming convention and file system layout for dependent modules. Modules would then do something as simple as.

```js
Hooks.once('token-action-hud-register', (core) => core.register(myVersionData, mySystemManager) )
```

**Comment by Larkinabout** [comment]
Sounds like a good solution. I'm just working it out as I go along so better ways of doing things are welcome. I'll have some time this evening to look at setting up a hook method. Are you on Discord? You can message me at Russell#7071.

**Comment by farling42** [comment]
I'm on the Foundry discord as Farling#9579

**Comment by farling42** [comment]
Maybe this discussion can continue on an issue in your new repository.

**Comment by Larkinabout** [comment]
https://github.com/Larkinabout/fvtt-token-action-hud-core/issues/32

**Pull request merged**
