### PR TITLE
Od6s v10 fixes

### PR DESCRIPTION
**Pull request by madseumas**
Makes Token Action HUD work with the 0.6.0 (FoundryVTT 10) version of OpenD6-Space.

### CODE REVIEW

**Comment by Larkinabout** [comment]
Hi @madseumas, would you be interested in developing a Token Action HUD OD6S module to work with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core)?

It should just be a case of shifting the OD6S-specific code over and updating to some new core functions. You can use [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) as a starting point. The only real requirement is the module id as the core module looks for the system module in the format: token-action-hud-system where system is the system id, e.g., token-action-hud-od6s.

If you're interested, let me know and I can help with getting started. I won't have the time to get to it myself anytime soon, so best for someone that supports the system.

**Comment by madseumas** [comment]
Hey, sorry I missed this.  I'd def be interested.  Let me know what steps I need to take to get started - I assume I'll need to create a github project and register the module with Foundry once ready?

**Comment by madseumas** [comment]
I was able to get it figured out - https://gitlab.com/vtt2/token-action-hud-opend6-space .  Thanks for breaking out the module this way, I'm sure that as systems get moved over to it it'll help with PR fatigue.

**Comment by Larkinabout** [comment]
Great news! I've added your module to the list of systems on Token Action HUD Core.

**Pull request merged**
