### PR TITLE
Update Lancer actions for v10 support

### PR DESCRIPTION
**Pull request by dodgepong**
This updates the Lancer functionality of TAH for v10 support.

Other changes:
* Adds new actions for Basic and Tech attacks for Mechs/NPCs
* Adds Mech shortcuts for Overcharge and Stabilize
* Moves the Grit roll to the Pilot tab on the Mech token actions, since Grit is a Pilot stat rather than a Mech stat

### CODE REVIEW

**Review by Larkinabout — APPROVED** [review]

**Comment by dodgepong** [comment]
Thanks so much for merging this!

What does the release cadence look like for this module? v10 support was just released for the Lancer system and this is one of the big modules many people are waiting on to be updated before they upgrade, so it would be nice to give people a sense of when that might happen.

**Comment by Larkinabout** [comment]
Hi @dodgepong , would you be interested in developing a Token Action HUD Lancer module to work with [Token Action HUD Core](https://foundryvtt.com/packages/token-action-hud-core)?

It should just be a case of shifting the Lancer-specific code over and updating to some new core functions. You can use [Token Action HUD D&D 5e](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) as a starting point. The only real requirement is the module id as the core module looks for the system module in the format: token-action-hud-**system** where **system** is the system id, e.g., token-action-hud-lancer.

If you're interested, let me know and I can help with getting started. I won't have the time to get to it myself anytime soon, so best for someone that supports the system.

**Comment by dodgepong** [comment]
I noticed the 5e repo and the Core work being done, is that the direction that you would prefer development move? I'll see if I can take a look at it. I assume that means that people would instead need to install TAH Core + the Lancer TAH module in the future?

**Comment by Larkinabout** [comment]
Yes, I won't personally be doing any feature development to the original Token Action HUD, so it's just bug fixes and pull requests from others until every existing system is supported via the Core/System modules structure.

I'm still planning to release an update for this version of the module soon, so your developments there will still be released. I've just released an update to Token Action HUD Core, so I thought now would be a good time to start development especially while it's fresh in your mind.

**Pull request merged**
