### PR TITLE
V11 pf2e compatibility

### PR DESCRIPTION
**Pull request by neo2005**
I fixed the problem with a v11

### CODE REVIEW

**Comment by Larkinabout** [comment]
Support for PF2e has moved to Token Action HUD Core[Token Action HUD Core](https://github.com/Larkinabout/fvtt-token-action-hud-core). Appreciate your efforts, but I won't be supporting two different versions of the HUD for PF2e.

**Comment by Zullock** [comment]
Hi, I can understand you not giving it support or developing new features for it, but this is a fix done by another person, why can't it be accepted so that those who want, can keep using it? We can do a fork and just add this fix, but it doesn't seem necessary to me, or am I missing something here?

**Comment by Larkinabout** [comment]
> Hi, I can understand you not giving it support or developing new features for it, but this is a fix done by another person, why can't it be accepted so that those who want, can keep using it? We can do a fork and just add this fix, but it doesn't seem necessary to me, or am I missing something here?

It's confusing enough for users and helpers to have two versions of Token Action HUD and even more confuseing for them to both support the same system. This division means that at least questions about the HUD can be resolved to which one is actively supporting the system. Until Token Action HUD Classic is completely archived.

I'm actively supporting Pathfinder 2 with Token Action HUD Core in Foundry VTT 10 and 11. If there are issues or reasons why you'd still want to use TAH Classic with this system, I'd prefer efforts are directed there. I happily accept pull requests over there.

I don't intend to support Token Action HUD Classic forever especially with a working replacement. Once system support is fully moved over, and more and more are, this version on Drental's repos can be archived.

I have no issue with forks for personal use and where its for personal use a fork makes more sense than getting someone else involved. For other users encourage them to swap over to Token Action HUD Core where there is active maintenance.

Hope that explains my reasons for not accepting this pull request. I had put a note in the readme to try to avoid developers spending time fixing systems no longer actively supported by this module. It might be a bit easy to miss, so I'll have a think about what else to do.

**Comment by Zullock** [comment]
The problem for a lot of people is that Token Action HUD Core had some significant changes with the user experience, and it's buggy sometimes, the other day we had a major bug where the whole module crashed for no reason, the settings going to default, some actions stop working and the strike menu disappearing for everyone and being replaced for “attacks” and it also tends to be more demanding on the computer for some reasons (foundry slow down for us with that module active, something that didn't happen with Classic). 

The crash didn't leave any log chat error and we can't replicate said error so we could try to fix it, so instead of thrusting that it won't happen again we decided to go back to classic since Idle's module (PF2e Interactive Token Tooltip) is not to our liking either.

All these issues makes it so that until HUD Core is in a better state we don't want to move on to that module, but right now we are playing in V11, so we needed to fix this one meanwhile to keep playing.

**Comment by Larkinabout** [comment]
I understand. In that instance, it makes sense to use your own fork.

If you would like to try using Token Action HUD Core, feel free to submit pull requests there or submit an issue and I'll take a look into it as and when I can. Additionally, Token Action HUD Core and the Token Action HUD system modules are always improving. There are fewer reports of significant issues and the userbase is strong, so you should be confident in it being even better when you try it in the future.

**Comment by fantasygmrguy** [comment]
I recently installed the PF2e HUD and the Core dependency remains unchecked. When I try to check it I get a message: "Cannot be  enabled due to issues in required dependencies"
I have removed all other modules to see if this could then be enabled but still got the same message. Thoughts?

**Pull request closed without merging**
